language: python
python:
#  - "2.7"
  - "3.4"
install:
  # Build/test dependencies
  - pip install -r requirements.txt

#before_script:
#  # Allow us to SSH passwordless to localhost
#  - ssh-keygen -f ~/.ssh/id_rsa -N ""
#  - cp ~/.ssh/{id_rsa.pub,authorized_keys}
#  # Creation of an SSH agent for testing forwarding
#  - eval $(ssh-agent)
#  - ssh-add

script:
  python -m unittest
#  # Normal tests
#  - fab test
#  # Integration tests
#  - fab -H localhost test:"--tests\=integration"
#  # Build docs; www first without warnings so its intersphinx objects file
#  # generates. Then docs (with warnings->errors), then www again (also w/
#  # warnings on.) FUN TIMES WITH CIRCULAR DEPENDENCIES.
#  - invoke www
#  - invoke docs -o -W
#  - invoke www -c -o -W

#notifications:
  recipients:
    - allenjiancan@gmail.com
  on_success: change
  on_failure: always
#  irc:
#    channels: "irc.freenode.org#fabric"
#    template:
#      - "%{repository}@%{branch}: %{message} (%{build_url})"
#    on_success: change
#    on_failure: change
#  email: false